insert into tbl_addresses (street, town, city) values ('4014 Rowland Circle', 'Tony', 'Åby');
insert into tbl_addresses (street, town, city) values ('90206 Warner Lane', 'Eagan', 'Kantharalak');
insert into tbl_addresses (street, town, city) values ('046 Johnson Crossing', 'Mesta', 'Inriville');
insert into tbl_addresses (street, town, city) values ('7 Mendota Parkway', 'Rigney', 'Kirove');
insert into tbl_addresses (street, town, city) values ('014 Garrison Street', 'Truax', 'Borova');
insert into tbl_addresses (street, town, city) values ('69 Kings Street', 'Waubesa', 'Xinshi');
insert into tbl_addresses (street, town, city) values ('796 Northfield Point', 'Muir', 'Al Qurayn');
insert into tbl_addresses (street, town, city) values ('7 Twin Pines Way', 'Waywood', 'Krasnaya Poyma');
insert into tbl_addresses (street, town, city) values ('479 Homewood Drive', 'Del Sol', 'Villa Florida');
insert into tbl_addresses (street, town, city) values ('55410 Kenwood Plaza', 'Sage', 'Da’ao');
insert into tbl_addresses (street, town, city) values ('21 Thierer Hill', 'Algoma', 'Dongyong');
insert into tbl_addresses (street, town, city) values ('440 Anthes Terrace', 'Schmedeman', 'Góra');
insert into tbl_addresses (street, town, city) values ('26 Logan Street', 'Birchwood', 'Québec');
insert into tbl_addresses (street, town, city) values ('3 Bartillon Drive', 'Troy', 'Huangbei');
insert into tbl_addresses (street, town, city) values ('51 Crescent Oaks Point', 'Mockingbird', 'Kitimat');
insert into tbl_addresses (street, town, city) values ('0 Harper Plaza', 'Maple Wood', 'Parychy');
insert into tbl_addresses (street, town, city) values ('49002 Farwell Junction', 'Clyde Gallagher', 'Łęczyce');
insert into tbl_addresses (street, town, city) values ('2 Pennsylvania Lane', 'Towne', 'Birmingham');
insert into tbl_addresses (street, town, city) values ('9346 7th Park', 'Holy Cross', 'Mwense');
insert into tbl_addresses (street, town, city) values ('1 Northview Court', 'American Ash', 'Terney');
insert into tbl_addresses (street, town, city) values ('512 Carpenter Street', 'Ruskin', 'Maria');
insert into tbl_addresses (street, town, city) values ('160 International Pass', 'Granby', 'Belang');
insert into tbl_addresses (street, town, city) values ('192 Eggendart Pass', 'Commercial', 'Dadeldhurā');
insert into tbl_addresses (street, town, city) values ('1 Jenna Place', 'Springview', 'Houba');
insert into tbl_addresses (street, town, city) values ('8 Trailsway Hill', 'Maple', 'Columbus');
insert into tbl_addresses (street, town, city) values ('28186 Carberry Court', 'Hooker', 'Huangli');
insert into tbl_addresses (street, town, city) values ('369 Forest Dale Junction', 'Southridge', 'Venustiano Carranza');
insert into tbl_addresses (street, town, city) values ('883 Carberry Drive', 'Beilfuss', '‘Aqrah');
insert into tbl_addresses (street, town, city) values ('07566 Spenser Pass', 'Judy', 'Dmytrivka');
insert into tbl_addresses (street, town, city) values ('441 Hoepker Crossing', 'Merry', 'Anchorage');
insert into tbl_addresses (street, town, city) values ('544 Mallard Point', 'Melrose', 'Bergen');
insert into tbl_addresses (street, town, city) values ('73530 Roxbury Street', 'Esch', 'Mayanhe');
insert into tbl_addresses (street, town, city) values ('37747 Lyons Lane', 'Di Loreto', 'Alicia');
insert into tbl_addresses (street, town, city) values ('868 Menomonie Crossing', 'Lunder', 'Ubud');
insert into tbl_addresses (street, town, city) values ('3074 Northport Parkway', 'Bultman', 'Mao');
insert into tbl_addresses (street, town, city) values ('6822 Delaware Court', 'Novick', 'Zhajin');
insert into tbl_addresses (street, town, city) values ('5 Fairfield Way', 'Twin Pines', 'Durazno');
insert into tbl_addresses (street, town, city) values ('85 Veith Center', 'Veith', 'Memaliaj');
insert into tbl_addresses (street, town, city) values ('84 Spenser Circle', 'Dixon', 'Zhougao');
insert into tbl_addresses (street, town, city) values ('4185 Dahle Crossing', 'Chive', 'Shimorskoye');
insert into tbl_addresses (street, town, city) values ('22 Katie Plaza', '7th', 'Suklayin');
insert into tbl_addresses (street, town, city) values ('4 Southridge Court', 'Warbler', 'Karis');
insert into tbl_addresses (street, town, city) values ('76 Graedel Crossing', 'Glacier Hill', 'Orissaare');
insert into tbl_addresses (street, town, city) values ('7397 Division Park', 'Debs', 'Pomahuaca');
insert into tbl_addresses (street, town, city) values ('71548 Jay Street', 'Bellgrove', 'Rychnov nad Kněžnou');
insert into tbl_addresses (street, town, city) values ('5129 Morning Crossing', 'Scoville', 'Sarulla');
insert into tbl_addresses (street, town, city) values ('18883 Cordelia Place', 'Basil', 'Samacá');
insert into tbl_addresses (street, town, city) values ('718 Meadow Valley Plaza', 'Ramsey', 'Sanshui');
insert into tbl_addresses (street, town, city) values ('8 Northwestern Place', 'Heffernan', 'Bielawa');
insert into tbl_addresses (street, town, city) values ('51 Tomscot Terrace', 'Anniversary', 'Rudnogorsk');
insert into tbl_addresses (street, town, city) values ('129 Mitchell Avenue', 'Farwell', 'Kabar Utara');
insert into tbl_addresses (street, town, city) values ('702 Prairie Rose Park', 'Boyd', 'Gulod');
insert into tbl_addresses (street, town, city) values ('5 Eliot Parkway', 'Logan', 'Qiaonan');
insert into tbl_addresses (street, town, city) values ('66 Northfield Street', 'Valley Edge', 'Tebingtinggi');
insert into tbl_addresses (street, town, city) values ('15521 Fallview Lane', 'Rowland', 'Jam');
insert into tbl_addresses (street, town, city) values ('729 Waywood Junction', 'Leroy', 'Pule');
insert into tbl_addresses (street, town, city) values ('0215 Browning Plaza', 'Mifflin', 'Bom Sucesso');
insert into tbl_addresses (street, town, city) values ('83 Jenna Point', 'Toban', 'Sudoměřice');
insert into tbl_addresses (street, town, city) values ('03847 Burning Wood Terrace', 'Armistice', 'Tuanshan');
insert into tbl_addresses (street, town, city) values ('221 Roxbury Crossing', 'Lakewood', 'Liufu');
insert into tbl_addresses (street, town, city) values ('69228 Talmadge Plaza', 'Kings', 'Cibungur');
insert into tbl_addresses (street, town, city) values ('88260 Northport Circle', 'Loomis', 'Bin’an');
insert into tbl_addresses (street, town, city) values ('90 Novick Place', 'Pierstorff', 'Bluri');
insert into tbl_addresses (street, town, city) values ('46853 Carpenter Road', 'Gulseth', 'Karítsa');
insert into tbl_addresses (street, town, city) values ('3979 Roxbury Drive', 'Swallow', 'Dzhayrakh');
insert into tbl_addresses (street, town, city) values ('71 Aberg Drive', '5th', 'Amiens');
insert into tbl_addresses (street, town, city) values ('2 Truax Place', 'Tennessee', 'Tây Hồ');
insert into tbl_addresses (street, town, city) values ('4212 Karstens Trail', 'Golf Course', 'Padre Nabeto');
insert into tbl_addresses (street, town, city) values ('52174 Grover Center', 'Troy', 'Sikasso');
insert into tbl_addresses (street, town, city) values ('82 Stone Corner Hill', 'Lerdahl', 'Belanting');
insert into tbl_addresses (street, town, city) values ('16152 Thackeray Drive', 'Mendota', 'Pereval''noe');
insert into tbl_addresses (street, town, city) values ('25 Holy Cross Crossing', 'Birchwood', 'Colorado Springs');
insert into tbl_addresses (street, town, city) values ('6036 Brickson Park Pass', '8th', 'Yumani');
insert into tbl_addresses (street, town, city) values ('554 Grayhawk Street', 'Waywood', 'Sao Hai');
insert into tbl_addresses (street, town, city) values ('4305 Tony Court', 'Jay', 'Katuli');
insert into tbl_addresses (street, town, city) values ('4774 Hanson Point', 'Trailsway', 'Gudong');
insert into tbl_addresses (street, town, city) values ('1 Manufacturers Road', 'Moland', 'Rora Timur');
insert into tbl_addresses (street, town, city) values ('3 Lighthouse Bay Alley', 'Oneill', 'Yedun');
insert into tbl_addresses (street, town, city) values ('7 Maple Crossing', 'Vahlen', 'Formiga');
insert into tbl_addresses (street, town, city) values ('992 La Follette Hill', 'Menomonie', 'Lajeosa');
insert into tbl_addresses (street, town, city) values ('57820 Manitowish Trail', 'Fremont', 'San Antonio');
insert into tbl_addresses (street, town, city) values ('90 Clove Alley', 'Pankratz', 'Shorko');
insert into tbl_addresses (street, town, city) values ('250 Meadow Ridge Trail', 'Beilfuss', 'Akademicheskoe');
insert into tbl_addresses (street, town, city) values ('0 Declaration Plaza', 'Troy', 'Wanjia');
insert into tbl_addresses (street, town, city) values ('109 Maryland Terrace', 'Sullivan', 'Muyaka');
insert into tbl_addresses (street, town, city) values ('4 Jana Center', 'Little Fleur', 'Bull Savanna');
insert into tbl_addresses (street, town, city) values ('10 Hayes Way', 'Columbus', 'São Félix do Xingu');
insert into tbl_addresses (street, town, city) values ('1 Farwell Court', 'Clyde Gallagher', 'Verkhnyachka');
insert into tbl_addresses (street, town, city) values ('562 Brickson Park Circle', 'Memorial', 'Dachang');
insert into tbl_addresses (street, town, city) values ('02105 Elmside Lane', 'Wayridge', 'West End');
insert into tbl_addresses (street, town, city) values ('16885 Hooker Court', 'Chinook', 'Piquete');
insert into tbl_addresses (street, town, city) values ('7 Meadow Vale Lane', 'Pleasure', 'Qarqania');
insert into tbl_addresses (street, town, city) values ('6015 Shasta Court', 'Sherman', 'Canela');
insert into tbl_addresses (street, town, city) values ('74 Onsgard Park', 'Barnett', 'Mianhu');
insert into tbl_addresses (street, town, city) values ('11843 Mendota Center', 'Browning', 'Morbatoh');
insert into tbl_addresses (street, town, city) values ('3 Nobel Hill', 'Burrows', 'Korczew');
insert into tbl_addresses (street, town, city) values ('6 Pleasure Alley', 'Charing Cross', 'Sumpur Kudus');
insert into tbl_addresses (street, town, city) values ('0 Blackbird Plaza', 'Prentice', 'Mundolsheim');
insert into tbl_addresses (street, town, city) values ('12022 Nelson Park', 'Browning', 'Leiyang');
insert into tbl_addresses (street, town, city) values ('3 Carioca Court', 'Park Meadow', 'Clermont-Ferrand');
insert into tbl_addresses (street, town, city) values ('5431 Pawling Street', 'Lotheville', 'Qaffīn');
insert into tbl_addresses (street, town, city) values ('65927 Sunnyside Park', 'Cody', 'Matou');
insert into tbl_addresses (street, town, city) values ('4725 Lotheville Trail', 'Kingsford', 'Zango');
insert into tbl_addresses (street, town, city) values ('37 Melby Pass', 'Knutson', 'Taganrog');
insert into tbl_addresses (street, town, city) values ('79 Jenna Parkway', 'Spaight', 'Birinci Aşıqlı');
insert into tbl_addresses (street, town, city) values ('1 Summit Place', 'Mitchell', 'Thị Trấn Yên Thịnh');
insert into tbl_addresses (street, town, city) values ('9 Crownhardt Court', 'Mesta', 'K Bang');
insert into tbl_addresses (street, town, city) values ('3271 Kennedy Street', 'Sundown', 'Zamoskvorech’ye');
insert into tbl_addresses (street, town, city) values ('9255 Debra Alley', 'Algoma', 'Göteborg');
insert into tbl_addresses (street, town, city) values ('492 Mifflin Parkway', 'School', 'Noebana');
insert into tbl_addresses (street, town, city) values ('3 Gulseth Alley', 'Lunder', 'Arhust');
insert into tbl_addresses (street, town, city) values ('181 Sugar Point', 'Orin', 'Mariestad');
insert into tbl_addresses (street, town, city) values ('057 Corben Alley', 'Declaration', 'Xinchang');
insert into tbl_addresses (street, town, city) values ('49 Dapin Parkway', 'Toban', 'Kavadarci');
insert into tbl_addresses (street, town, city) values ('684 Sachtjen Terrace', 'John Wall', 'Bida');
insert into tbl_addresses (street, town, city) values ('2305 Monument Junction', 'Village Green', 'Maicao');
insert into tbl_addresses (street, town, city) values ('504 Hollow Ridge Point', 'Grasskamp', 'San Rafael');
insert into tbl_addresses (street, town, city) values ('869 Roth Road', 'Heath', 'Sopron');
insert into tbl_addresses (street, town, city) values ('604 Cottonwood Way', 'Nancy', 'Gävle');
insert into tbl_addresses (street, town, city) values ('6262 Myrtle Plaza', 'Crowley', 'Al Jadīd');
insert into tbl_addresses (street, town, city) values ('89925 Jenna Parkway', 'Dennis', 'Laohekou');
insert into tbl_addresses (street, town, city) values ('365 Bowman Hill', 'Golf View', 'Nama');
insert into tbl_addresses (street, town, city) values ('7 Scofield Alley', 'Monterey', 'Catania');
insert into tbl_addresses (street, town, city) values ('0 Express Place', 'Dawn', 'Kajaani');
insert into tbl_addresses (street, town, city) values ('11084 Troy Place', 'Browning', 'Tamontaka');
insert into tbl_addresses (street, town, city) values ('2 Loftsgordon Place', 'Lotheville', 'Kampungbaru');
insert into tbl_addresses (street, town, city) values ('5 Arizona Street', 'Stone Corner', 'Guohua');
insert into tbl_addresses (street, town, city) values ('22 Longview Way', 'Magdeline', 'Oldřišov');
insert into tbl_addresses (street, town, city) values ('322 La Follette Place', 'Morrow', 'Klichaw');
insert into tbl_addresses (street, town, city) values ('70125 Knutson Junction', 'Upham', 'Koungheul');
insert into tbl_addresses (street, town, city) values ('35 Bartelt Plaza', 'Judy', 'Nangan');
insert into tbl_addresses (street, town, city) values ('615 Kinsman Avenue', 'Declaration', 'Saint-Sauveur');
insert into tbl_addresses (street, town, city) values ('8312 1st Junction', 'Haas', 'Sartana');
insert into tbl_addresses (street, town, city) values ('75 Hoepker Street', 'Washington', 'Umingan');
insert into tbl_addresses (street, town, city) values ('5 Westerfield Court', 'Troy', 'Ketawang');
insert into tbl_addresses (street, town, city) values ('02 High Crossing Avenue', 'Killdeer', 'Baie-D''Urfé');
insert into tbl_addresses (street, town, city) values ('95 Brickson Park Park', 'Barnett', 'Sintansin');
insert into tbl_addresses (street, town, city) values ('364 Swallow Hill', 'School', 'Banjar Pangkungtibah Selatan');
insert into tbl_addresses (street, town, city) values ('6 Stone Corner Terrace', 'Myrtle', 'Markaz Mudhaykirah');
insert into tbl_addresses (street, town, city) values ('49 Forest Pass', 'Oxford', 'Midland');
insert into tbl_addresses (street, town, city) values ('3077 4th Drive', 'Arapahoe', 'Lipovci');
insert into tbl_addresses (street, town, city) values ('83143 Mallory Pass', 'Maywood', 'Datian');
insert into tbl_addresses (street, town, city) values ('282 Ruskin Terrace', 'Boyd', 'Welkom');
insert into tbl_addresses (street, town, city) values ('2838 Carey Circle', 'Burning Wood', 'Al Hāshimīyah');
insert into tbl_addresses (street, town, city) values ('31 Commercial Parkway', 'Sycamore', 'Xylotymbou');
insert into tbl_addresses (street, town, city) values ('7 Lake View Parkway', 'Charing Cross', 'Água Retorta');
insert into tbl_addresses (street, town, city) values ('4618 Anzinger Point', 'Dunning', 'Tanbu');
insert into tbl_addresses (street, town, city) values ('057 Badeau Pass', 'Memorial', 'San Jose');
insert into tbl_addresses (street, town, city) values ('023 Thackeray Plaza', 'Southridge', 'San Carlos');
insert into tbl_addresses (street, town, city) values ('1847 Surrey Trail', 'Bluestem', 'Muting');
insert into tbl_addresses (street, town, city) values ('354 Sommers Park', 'Oak', 'Whitegate');
insert into tbl_addresses (street, town, city) values ('07 Monument Junction', 'Cordelia', 'Ijuí');
insert into tbl_addresses (street, town, city) values ('49 Jay Crossing', 'Valley Edge', 'Eindhoven');
insert into tbl_addresses (street, town, city) values ('6237 Kinsman Center', 'Hallows', 'Buseresere');
insert into tbl_addresses (street, town, city) values ('5319 Katie Street', 'Stang', 'Cibenda');
insert into tbl_addresses (street, town, city) values ('06 Paget Junction', 'Washington', 'Dohār');
insert into tbl_addresses (street, town, city) values ('19 Gateway Lane', 'Everett', 'Yuannan');
insert into tbl_addresses (street, town, city) values ('3924 Bonner Court', 'Clemons', 'Tuatuka');
insert into tbl_addresses (street, town, city) values ('5 Green Ridge Avenue', 'Bartelt', 'Zhoujiaba');
insert into tbl_addresses (street, town, city) values ('100 Quincy Circle', 'Londonderry', 'Sembungan Kidul');
insert into tbl_addresses (street, town, city) values ('86239 Florence Drive', 'Summit', 'Dalkey');
insert into tbl_addresses (street, town, city) values ('5216 Donald Court', 'Continental', 'Torino');
insert into tbl_addresses (street, town, city) values ('4646 Nova Trail', 'Cambridge', 'Banyuresmi');
insert into tbl_addresses (street, town, city) values ('444 Forest Dale Avenue', 'Schurz', 'Yonkers');
insert into tbl_addresses (street, town, city) values ('77 Lukken Drive', 'Melvin', 'Gedian');
insert into tbl_addresses (street, town, city) values ('4 Colorado Avenue', 'Brown', 'Macapsing');
insert into tbl_addresses (street, town, city) values ('612 7th Crossing', 'Melrose', 'Kista');
insert into tbl_addresses (street, town, city) values ('93 Lyons Drive', 'Harper', 'Illela');
insert into tbl_addresses (street, town, city) values ('67411 Spaight Point', 'Merchant', 'Gongju');
insert into tbl_addresses (street, town, city) values ('40 Shoshone Circle', 'Fallview', 'Mangge');
insert into tbl_addresses (street, town, city) values ('24 Cherokee Road', 'Village', 'Al Wardānīn');
insert into tbl_addresses (street, town, city) values ('9 Nova Parkway', 'Anzinger', 'Aksarka');
insert into tbl_addresses (street, town, city) values ('75094 Northfield Street', 'Rowland', 'Ganné Tiqwa');
insert into tbl_addresses (street, town, city) values ('104 Pine View Court', 'Prentice', 'Youkaichi');
insert into tbl_addresses (street, town, city) values ('79 Leroy Drive', 'Gerald', '‘Aşīrah ash Shamālīyah');
insert into tbl_addresses (street, town, city) values ('702 Graedel Park', 'Chive', 'Ningdun');
insert into tbl_addresses (street, town, city) values ('142 Cottonwood Road', 'Bluejay', 'Benoni');
insert into tbl_addresses (street, town, city) values ('07 Morrow Circle', 'Lien', 'Kampungraja');
insert into tbl_addresses (street, town, city) values ('0455 Gerald Park', 'Twin Pines', 'Nordeste');
insert into tbl_addresses (street, town, city) values ('14 Memorial Pass', 'Glacier Hill', 'Ciganaria');
insert into tbl_addresses (street, town, city) values ('9 Meadow Ridge Plaza', 'Melrose', 'Sabnie');
insert into tbl_addresses (street, town, city) values ('1 Thompson Drive', 'Arrowood', 'Makamba');
insert into tbl_addresses (street, town, city) values ('83 Sachs Road', 'Paget', 'Valday');
insert into tbl_addresses (street, town, city) values ('045 Eastlawn Pass', 'Clemons', 'Shaochang');
insert into tbl_addresses (street, town, city) values ('18 Atwood Plaza', 'Myrtle', 'Entradas');
insert into tbl_addresses (street, town, city) values ('3981 Lotheville Avenue', 'Briar Crest', 'Lanchyn');
insert into tbl_addresses (street, town, city) values ('70776 Hanover Place', 'Upham', 'Muli');
insert into tbl_addresses (street, town, city) values ('6013 Northwestern Junction', 'Northwestern', 'Balindong');
insert into tbl_addresses (street, town, city) values ('34641 Hansons Park', 'Ludington', 'Kunting');
insert into tbl_addresses (street, town, city) values ('343 Mosinee Lane', 'Glacier Hill', 'Beylagan');
insert into tbl_addresses (street, town, city) values ('96646 Scofield Drive', 'Farragut', 'Opatov');
insert into tbl_addresses (street, town, city) values ('0165 Loftsgordon Parkway', 'Victoria', 'Uppsala');
insert into tbl_addresses (street, town, city) values ('5 Golf View Circle', 'Vernon', 'Taling Chan');
insert into tbl_addresses (street, town, city) values ('1 Stephen Parkway', 'Warrior', 'Gasa');
insert into tbl_addresses (street, town, city) values ('86078 Kennedy Place', 'Forest Dale', 'Stratford');
insert into tbl_addresses (street, town, city) values ('64 Union Road', 'Aberg', 'Courelas Bravas');
insert into tbl_addresses (street, town, city) values ('70 Weeping Birch Circle', 'Bashford', 'Karangcombong');
insert into tbl_addresses (street, town, city) values ('2 Jana Junction', 'Emmet', 'Vërtop');
insert into tbl_addresses (street, town, city) values ('16620 Golf Course Junction', 'Vidon', 'Dinskaya');
insert into tbl_addresses (street, town, city) values ('74230 Lerdahl Point', 'Eagle Crest', 'Huxingshan');
insert into tbl_addresses (street, town, city) values ('6 Oak Valley Terrace', 'Elka', 'Kertosari');
insert into tbl_addresses (street, town, city) values ('7975 Waubesa Avenue', 'Sutherland', 'Hobscheid');
insert into tbl_addresses (street, town, city) values ('241 Algoma Terrace', 'Troy', 'Parengan');
insert into tbl_addresses (street, town, city) values ('04942 Buell Way', 'Westport', 'San Salvador');
insert into tbl_addresses (street, town, city) values ('5 Columbus Pass', 'Fieldstone', 'Chóra');
insert into tbl_addresses (street, town, city) values ('7810 Hoard Place', 'Birchwood', 'Weiyanggong');
insert into tbl_addresses (street, town, city) values ('56539 Vernon Terrace', 'Del Sol', 'Vranisht');
insert into tbl_addresses (street, town, city) values ('2 Thompson Road', 'Petterle', 'Zhuozishan');
insert into tbl_addresses (street, town, city) values ('8346 Main Crossing', 'Westridge', 'Крива Паланка');
insert into tbl_addresses (street, town, city) values ('57 Eggendart Point', 'American', 'Baitao');
insert into tbl_addresses (street, town, city) values ('064 Clarendon Hill', 'Toban', 'Magong');
insert into tbl_addresses (street, town, city) values ('5421 Dakota Park', 'Ruskin', 'Nasilava');
insert into tbl_addresses (street, town, city) values ('47421 Mifflin Court', 'Karstens', 'Ar Ramāḑīn');
insert into tbl_addresses (street, town, city) values ('296 Westend Way', 'Warner', 'Weiwangzhuang');
insert into tbl_addresses (street, town, city) values ('707 Gateway Trail', 'Dottie', 'Thap Khlo');
insert into tbl_addresses (street, town, city) values ('41 Independence Point', 'Dapin', 'Itauguá');
insert into tbl_addresses (street, town, city) values ('3290 Cottonwood Court', 'Sullivan', 'Non Sung');
insert into tbl_addresses (street, town, city) values ('95 Washington Park', 'Meadow Vale', 'Strelitsa');
insert into tbl_addresses (street, town, city) values ('3141 Atwood Hill', 'Browning', 'Kafr az Zayyāt');
insert into tbl_addresses (street, town, city) values ('7 Clarendon Alley', 'Kings', 'Gengqing');
insert into tbl_addresses (street, town, city) values ('7948 Park Meadow Lane', 'Forest Dale', 'Nogueira');
insert into tbl_addresses (street, town, city) values ('17553 Summerview Pass', 'Kensington', 'Cumba');
insert into tbl_addresses (street, town, city) values ('9 Ramsey Way', 'Valley Edge', 'Semampirbarat');
insert into tbl_addresses (street, town, city) values ('99 Mendota Lane', 'Oriole', 'Mobile');
insert into tbl_addresses (street, town, city) values ('99 Tennyson Road', 'Charing Cross', 'Baiquan');
insert into tbl_addresses (street, town, city) values ('6 Moulton Junction', 'Mendota', 'Astorga');
insert into tbl_addresses (street, town, city) values ('81640 Lake View Road', 'Di Loreto', 'Hedi');
insert into tbl_addresses (street, town, city) values ('89912 Rockefeller Park', 'Rieder', 'Yantang');
insert into tbl_addresses (street, town, city) values ('90255 Fuller Court', 'Columbus', 'Luziânia');
insert into tbl_addresses (street, town, city) values ('7846 Donald Way', 'Nobel', 'Nowe Warpno');
insert into tbl_addresses (street, town, city) values ('43633 Talmadge Road', 'Di Loreto', 'Zizhao');
insert into tbl_addresses (street, town, city) values ('0021 Harbort Park', 'Monterey', 'Isangel');
insert into tbl_addresses (street, town, city) values ('24 Amoth Alley', 'Hayes', 'Vito');
insert into tbl_addresses (street, town, city) values ('831 Ruskin Road', 'Farmco', 'Capela');
insert into tbl_addresses (street, town, city) values ('15 Pleasure Pass', 'Hooker', 'Badajoz');
insert into tbl_addresses (street, town, city) values ('81804 Reindahl Trail', 'Starling', 'Winschoten');
insert into tbl_addresses (street, town, city) values ('41089 Annamark Parkway', 'Anthes', 'Tuxi');
insert into tbl_addresses (street, town, city) values ('38 Raven Point', 'Atwood', 'Şaḩam');
insert into tbl_addresses (street, town, city) values ('29 Tony Avenue', 'Old Shore', 'A’ershan');
insert into tbl_addresses (street, town, city) values ('1826 Hooker Crossing', 'Steensland', 'El Paso');
insert into tbl_addresses (street, town, city) values ('5870 Gulseth Crossing', 'Hoepker', 'Las Flores');
insert into tbl_addresses (street, town, city) values ('1 Bowman Plaza', 'Brickson Park', 'Josefina');
insert into tbl_addresses (street, town, city) values ('43 Buhler Circle', 'Towne', 'Nanzhai');
insert into tbl_addresses (street, town, city) values ('17 Dorton Road', 'Southridge', 'Zlaté Hory');
insert into tbl_addresses (street, town, city) values ('99 Village Terrace', 'Schurz', 'Jiasi');
insert into tbl_addresses (street, town, city) values ('1 Dahle Road', 'Dawn', 'Napuro');
insert into tbl_addresses (street, town, city) values ('69 Eagle Crest Parkway', 'Pearson', 'Repki');
insert into tbl_addresses (street, town, city) values ('961 Armistice Junction', 'Lake View', 'Shilovo');
insert into tbl_addresses (street, town, city) values ('82156 Bowman Court', 'Moulton', 'Juḩr ad Dīk');
insert into tbl_addresses (street, town, city) values ('36 Dwight Road', 'Evergreen', 'Samdo');
insert into tbl_addresses (street, town, city) values ('730 Clemons Street', 'Algoma', 'Pedra Furada');
insert into tbl_addresses (street, town, city) values ('08417 Vernon Crossing', 'Browning', 'Majagual');
insert into tbl_addresses (street, town, city) values ('6 Red Cloud Park', 'Sunbrook', 'Kabardinka');
insert into tbl_addresses (street, town, city) values ('2 Lakewood Gardens Alley', 'Arapahoe', 'Torre');
insert into tbl_addresses (street, town, city) values ('0450 Ramsey Drive', 'Maywood', 'Na Khu');
insert into tbl_addresses (street, town, city) values ('70920 Westend Junction', 'Eggendart', 'Pampa del Infierno');
insert into tbl_addresses (street, town, city) values ('70390 Ridgeview Drive', 'Declaration', 'Tanxi');
insert into tbl_addresses (street, town, city) values ('1565 Holy Cross Terrace', 'Colorado', 'Meipu');
insert into tbl_addresses (street, town, city) values ('6 Stoughton Junction', 'American Ash', 'Melaka');
insert into tbl_addresses (street, town, city) values ('46263 Burrows Crossing', 'Coleman', 'Thị Trấn Phước Bửu');
insert into tbl_addresses (street, town, city) values ('40 North Trail', 'Rowland', 'Lagoaça');
insert into tbl_addresses (street, town, city) values ('26 Armistice Place', 'Rusk', 'Jianxin');
insert into tbl_addresses (street, town, city) values ('56254 Blackbird Crossing', 'Fieldstone', 'Hämeenkoski');
insert into tbl_addresses (street, town, city) values ('234 Monument Court', 'Manitowish', 'Itoigawa');
insert into tbl_addresses (street, town, city) values ('88034 Independence Center', 'Milwaukee', 'Shangkuli');
insert into tbl_addresses (street, town, city) values ('76 Thompson Point', 'Truax', 'Gikongoro');
insert into tbl_addresses (street, town, city) values ('5 Waywood Drive', 'Fairfield', 'Aldeia de Juzo');
insert into tbl_addresses (street, town, city) values ('24589 Vernon Crossing', 'Golf Course', 'Paprotnia');
insert into tbl_addresses (street, town, city) values ('11 Cascade Terrace', 'Clyde Gallagher', 'Skála');
insert into tbl_addresses (street, town, city) values ('2 Hagan Court', 'Sundown', 'Kandun');
insert into tbl_addresses (street, town, city) values ('1 Manley Park', 'Trailsway', 'Soeng Sang');
insert into tbl_addresses (street, town, city) values ('0908 Armistice Junction', 'Independence', 'Villanueva');
insert into tbl_addresses (street, town, city) values ('77 Waubesa Lane', 'Farmco', 'Washington');
insert into tbl_addresses (street, town, city) values ('1 Main Place', 'Magdeline', 'Fangcun');
insert into tbl_addresses (street, town, city) values ('8 Tennessee Park', 'Bartelt', 'Saint-Eustache');
insert into tbl_addresses (street, town, city) values ('16348 Park Meadow Center', 'Portage', 'Shi’ao');
insert into tbl_addresses (street, town, city) values ('732 Rowland Street', 'Farragut', 'Lille');
insert into tbl_addresses (street, town, city) values ('1 Alpine Alley', 'Coleman', 'Dihtyari');
insert into tbl_addresses (street, town, city) values ('1 Division Junction', 'Scofield', 'Kedungtaman');
insert into tbl_addresses (street, town, city) values ('351 Anthes Hill', 'Ronald Regan', 'Wakuya');
insert into tbl_addresses (street, town, city) values ('71838 Summit Lane', 'Surrey', 'São Mateus do Maranhão');
insert into tbl_addresses (street, town, city) values ('352 Eastwood Alley', 'Schlimgen', 'Krasyliv');
insert into tbl_addresses (street, town, city) values ('460 Esch Circle', 'Luster', 'Predavac');
insert into tbl_addresses (street, town, city) values ('45813 Calypso Plaza', 'Meadow Vale', 'Ninove');
insert into tbl_addresses (street, town, city) values ('3179 Hudson Point', 'Maywood', 'São Francisco do Conde');
insert into tbl_addresses (street, town, city) values ('73650 Golden Leaf Circle', 'Tomscot', 'Ourinhos');
insert into tbl_addresses (street, town, city) values ('26841 Acker Trail', 'Arapahoe', 'Arcos de Valdevez');
insert into tbl_addresses (street, town, city) values ('4497 Trailsway Drive', 'Susan', 'Vänersborg');
insert into tbl_addresses (street, town, city) values ('734 Susan Court', 'Dixon', 'Fengchan');
insert into tbl_addresses (street, town, city) values ('6900 Kennedy Hill', 'Graedel', 'São Francisco');
insert into tbl_addresses (street, town, city) values ('21445 Weeping Birch Parkway', 'Algoma', 'Jackson');
insert into tbl_addresses (street, town, city) values ('98 Birchwood Street', 'Chinook', 'Chojna');
insert into tbl_addresses (street, town, city) values ('250 West Pass', 'Brentwood', 'Khōshī');
insert into tbl_addresses (street, town, city) values ('013 Pennsylvania Junction', 'Monterey', 'Uralets');
insert into tbl_addresses (street, town, city) values ('0 Bobwhite Point', 'Paget', 'Sumberrojokrajan');
insert into tbl_addresses (street, town, city) values ('80 Kingsford Junction', 'Coleman', 'Paris 08');
insert into tbl_addresses (street, town, city) values ('460 Barnett Trail', 'Shelley', 'Longxi');
insert into tbl_addresses (street, town, city) values ('0467 Arapahoe Point', 'Eagle Crest', 'Pategi');
insert into tbl_addresses (street, town, city) values ('9477 3rd Terrace', 'Vidon', 'Foluo');
insert into tbl_addresses (street, town, city) values ('3591 Lien Street', 'Hauk', 'Monte');
